# Generated by Django 2.1.7 on 2019-07-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sales_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='orderid',
            field=models.CharField(blank=True, default='', max_length=200, null=True, unique=True),
        ),
    ]
