# Generated by Django 2.1.7 on 2019-08-03 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190730_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchStatus',
            fields=[
                ('name', models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.BatchStatus'),
        ),
    ]
