# Generated by Django 2.1.7 on 2019-07-01 20:21

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='batch',
            fields=[
                ('quant', models.IntegerField(default=0)),
                ('unit_price', models.FloatField(default=0.0)),
                ('batchid', models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('minselling', models.FloatField(default=0)),
                ('date', models.DateField(auto_now=True)),
                ('total_cost', models.FloatField(default=0.0)),
                ('profit10', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='currency',
            fields=[
                ('name', models.CharField(default='USD', max_length=100, primary_key=True, serialize=False)),
                ('exrate', models.FloatField(default=3.75)),
            ],
        ),
        migrations.CreateModel(
            name='feeprog',
            fields=[
                ('name', models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('addfee', models.FloatField(default=0)),
                ('mulfee', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('name', models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('product_type', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('rimage', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to=main.models.filename_generator)),
                ('description', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('avalible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.IntegerField()),
                ('saleprice', models.FloatField()),
                ('unitprofit', models.FloatField(default=0.0)),
                ('profitpercent', models.FloatField(default=0.0)),
                ('totalprofit', models.FloatField(default=0.0)),
                ('profit', models.FloatField(default=0.0)),
                ('date', models.DateField(auto_now=True)),
                ('batchid', models.ForeignKey(blank=True, limit_choices_to=models.Q(quant__gt=0), null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.batch')),
                ('product_type', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.product')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.currency'),
        ),
        migrations.AddField(
            model_name='batch',
            name='feeprog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.feeprog'),
        ),
        migrations.AddField(
            model_name='batch',
            name='product_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.product'),
        ),
    ]
