# Generated by Django 2.1.4 on 2018-12-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('batchid', models.CharField(default='', max_length=100, unique=True)),
                ('typestr', models.CharField(default='', max_length=100, unique=True)),
                ('price', models.CharField(default='', max_length=100, unique=True)),
            ],
        ),
    ]
