# Generated by Django 2.2.4 on 2019-08-20 18:42

from django.db import migrations, models
import django.db.models.deletion
import main.models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# main.migrations.0007_auto_20190811_1706

class Migration(migrations.Migration):

    def StaticsDefault(apps, schema_editor):
        Statics=apps.get_model('main','Statics')
        stat=Statics()
        stat.name='capital'
        stat.value=0
        stat.save()
        stat=Statics()
        stat.name='total'
        stat.value=0
        stat.save()
    replaces = [('main', '0001_initial'), ('main', '0002_sales_orderid'), ('main', '0003_auto_20190715_2006'), ('main', '0004_auto_20190730_1951'), ('main', '0005_auto_20190803_1423'), ('main', '0007_auto_20190811_1706'), ('main', '0006_auto_20190811_1705'), ('main', '0008_merge_20190811_1707'), ('main', '0009_auto_20190811_2238'), ('main', '0010_auto_20190818_2206'), ('main', '0011_auto_20190819_1850')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='currency',
            fields=[
                ('name', models.CharField(default='USD', max_length=100, primary_key=True, serialize=False)),
                ('exrate', models.FloatField(default=3.75)),
            ],
        ),
        migrations.CreateModel(
            name='feeprog',
            fields=[
                ('name', models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('addfee', models.FloatField(default=0)),
                ('mulfee', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('name', models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('product_type', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('rimage', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to=main.models.filename_generator)),
                ('description', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('avalible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='batch',
            fields=[
                ('quant', models.IntegerField(default=0)),
                ('unit_price', models.FloatField(default=0.0)),
                ('batchid', models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('minselling', models.FloatField(default=0)),
                ('date', models.DateField(auto_now=True)),
                ('total_cost', models.FloatField(default=0.0)),
                ('profit10', models.FloatField(default=0.0)),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.currency')),
                ('feeprog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.feeprog')),
                ('product_type', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.product')),
            ],
            options={
                'ordering': ['quant'],
            },
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.IntegerField()),
                ('saleprice', models.FloatField()),
                ('unitprofit', models.FloatField(default=0.0)),
                ('profitpercent', models.FloatField(default=0.0)),
                ('totalprofit', models.FloatField(default=0.0)),
                ('profit', models.FloatField(default=0.0)),
                ('date', models.DateField(auto_now=True)),
                ('batchid', models.ForeignKey(blank=True, limit_choices_to=models.Q(quant__gt=0), null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.batch')),
                ('product_type', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.product')),
                ('orderid', models.CharField(blank=True, default='', max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BatchStatus',
            fields=[
                ('name', models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.BatchStatus'),
        ),
        migrations.RunPython(StaticsDefault),
        migrations.AddField(
            model_name='batchstatus',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('name', models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('value', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]