# Generated by Django 3.0.7 on 2020-06-16 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.IntegerField(default=0)),
                ('unit_price', models.FloatField(default=0.0)),
                ('batch_id', models.CharField(default='', max_length=100, unique=True)),
                ('min_selling', models.FloatField(default=0)),
                ('total_cost', models.FloatField(default=0.0)),
                ('profit10', models.FloatField(default=0.0)),
                ('date', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['quant'],
            },
        ),
        migrations.CreateModel(
            name='BatchStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True)),
                ('cost', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='USD', max_length=100, unique=True)),
                ('exchange_rate', models.FloatField(default=3.75)),
            ],
        ),
        migrations.CreateModel(
            name='fee_prog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True)),
                ('add_fee', models.FloatField(default=0)),
                ('multiply_fee', models.FloatField(default=1)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(default='', max_length=100, unique=True)),
                ('name', models.CharField(default='', max_length=100, unique=True)),
                ('product_type', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('avalible', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True)),
                ('value', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.IntegerField()),
                ('sale_price', models.FloatField()),
                ('unit_profit', models.FloatField(default=0.0)),
                ('profit_percent', models.FloatField(default=0.0)),
                ('total_profit', models.FloatField(default=0.0)),
                ('profit', models.FloatField(default=0.0)),
                ('date', models.DateField(auto_now=True)),
                ('order_id', models.CharField(blank=True, default='', max_length=200, null=True, unique=True)),
                ('batch_id', models.ForeignKey(blank=True, limit_choices_to=models.Q(quant__gt=0), null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.batch')),
                ('product_type', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.product')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.currency'),
        ),
        migrations.AddField(
            model_name='batch',
            name='fee_prog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.fee_prog'),
        ),
        migrations.AddField(
            model_name='batch',
            name='product_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.product'),
        ),
        migrations.AddField(
            model_name='batch',
            name='status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.BatchStatus'),
        ),
    ]
