# Generated by Django 2.1.4 on 2018-12-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='currency',
            fields=[
                ('name', models.CharField(default='USD', max_length=100, primary_key=True, serialize=False)),
                ('exrate', models.FloatField(default=3.75)),
            ],
        ),
    ]
