# Generated by Django 3.0.7 on 2020-07-10 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='asin',
            new_name='unique_id',
        ),
    ]
