# Generated by Django 2.1.4 on 2018-12-12 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.IntegerField()),
                ('unitprice', models.FloatField()),
                ('uid', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typestr', models.CharField(default='', max_length=100)),
                ('saleprice', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.IntegerField()),
                ('saleprice', models.FloatField()),
                ('profit', models.FloatField()),
                ('batchid', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.batch')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='batchid',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='ProductsImages'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='typestr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.commission'),
        ),
        migrations.AddField(
            model_name='sales',
            name='productname',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.product'),
        ),
        migrations.AddField(
            model_name='batch',
            name='productname',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.product'),
        ),
    ]
