# Generated by Django 2.1.7 on 2019-07-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='orderid',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
