# Generated by Django 2.1.4 on 2018-12-13 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181212_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commission',
            old_name='saleprice',
            new_name='fee',
        ),
        migrations.RenameField(
            model_name='commission',
            old_name='typestr',
            new_name='productname',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='typestr',
            new_name='productname',
        ),
    ]
