# Generated by Django 2.2.4 on 2019-09-23 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190923_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeprog',
            options={'ordering': ['name']},
        ),
    ]
