# Generated by Django 2.1.4 on 2018-12-17 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.currency'),
        ),
    ]
