# Generated by Django 2.1.4 on 2018-12-18 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_batch_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='batchid',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(quant__gt=0), null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.batch'),
        ),
    ]
