# Generated by Django 2.1.4 on 2018-12-13 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181213_0546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='productname',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='commission',
            old_name='productname',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productname',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='productname',
            new_name='product_name',
        ),
    ]
