# Generated by Django 2.1.7 on 2019-07-30 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190715_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['quant']},
        ),
    ]
