# Generated by Django 2.1.4 on 2018-12-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181216_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='id',
        ),
        migrations.AlterField(
            model_name='batch',
            name='uid',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
