# Generated by Django 2.1.4 on 2018-12-18 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181218_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='time',
            new_name='date',
        ),
    ]
