# Generated by Django 2.1.4 on 2018-12-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181218_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='profitpercent',
            field=models.FloatField(default=0.0),
        ),
    ]
