# Generated by Django 2.1.4 on 2018-12-13 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181213_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='product_name',
            new_name='product_type',
        ),
        migrations.RenameField(
            model_name='commission',
            old_name='product_name',
            new_name='product_type',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='product_type',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='product_name',
            new_name='product_type',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.commission', to_field='product_name'),
        ),
    ]
