# Generated by Django 2.1.4 on 2018-12-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181219_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='total_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='rimage',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='ProductsImages'),
        ),
    ]
