# Generated by Django 2.1.7 on 2019-08-11 17:06

from django.db import migrations


def StaticsDefault(apps, schema_editor):
    Statics=apps.get_model('main','Statics')
    stat=Statics()
    stat.name='capital'
    stat.value=0
    stat.save()
    stat=Statics()
    stat.name='total'
    stat.value=0
    stat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190803_1423'),
    ]

    operations = [
        migrations.RunPython(StaticsDefault),
    ]