# Generated by Django 2.1.7 on 2019-08-11 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190811_1705'),
        ('main', '0007_auto_20190811_1706'),
    ]

    operations = [
    ]
