# Generated by Django 2.1.7 on 2019-08-11 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_merge_20190811_1707'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statics',
            new_name='Statistics',
        ),
    ]
